### ISSUE TITLE
Can't sync color when switching theme (light/dark) mode in Docusaurus v3.5.0 & MUI v6

### ISSUE THREAD

**Issue by namnguyenthanhwork** [namnguyenthanhwork/docusaurus-material-ui-template#3]
When switching theme, localstorage updates theme, color of Docusaurus theme synced, but variable of MUI does not sync it.

<img width="1721" alt="image" src="https://github.com/user-attachments/assets/cc8d1e14-b9bd-4cc3-b9ab-287bcef5e736">

**Comment by sszczep** [comment]
You can sync with local storage using the following `ThemeProvider` props:
```
colorSchemeStorageKey="theme"
modeStorageKey="theme"
```

It's also a good idea to set `defaultMode` to default color mode defined in docusaurus config, so it doesn't break on first load after clearing local storage.

**Comment by namnguyenthanhwork** [comment]
Problem resolved at #5
